"use client";
import { CheckCircle2, Copy, KeyRound, LogOut, Mail, MonitorSmartphone, ShieldCheck, UserRound } from "lucide-react";
import { useState } from "react";
import { PageHeader, Panel, Toggle } from "@/components/ui";

export function AccountClient({ envInfo }: { envInfo:{hasPassword:boolean; authType:string; version:string}}){
  const [tab,setTab]=useState<"プロフィール"|"セキュリティ"|"セッション">("プロフィール");
  return <div className="workspace-page"><PageHeader title="アカウント" description="管理者プロフィール、認証、現在のセッションを管理します。"/>
    <div className="account-shell"><div className="account-card"><div className="account-avatar"><UserRound size={34}/></div><div><h2>Admin User</h2><p>admin@salesgate.local</p><span><CheckCircle2 size={13}/>管理者 · v{envInfo.version}</span></div></div><div className="account-tabs"><button className={tab==="プロフィール"?"active":""} onClick={()=>setTab("プロフィール")}>プロフィール</button><button className={tab==="セキュリティ"?"active":""} onClick={()=>setTab("セキュリティ")}>セキュリティ</button><button className={tab==="セッション"?"active":""} onClick={()=>setTab("セッション")}>セッション</button></div>
      {tab==="プロフィール"? <Panel className="account-panel"><div className="account-section-head"><UserRound size={18}/><div><h3>プロフィール情報</h3><p>SalesGate上で表示される管理者情報。</p></div></div><div className="form-grid"><label>表示名<input defaultValue="Admin User" readOnly style={{opacity:0.7}}/></label><label>役割<input defaultValue="管理者" readOnly style={{opacity:0.7}}/></label><label className="full">メールアドレス<div className="input-with-icon"><Mail size={14}/><input defaultValue="admin@salesgate.local" readOnly style={{opacity:0.7}}/></div></label></div><div className="modal-info" style={{margin:"13px 14px"}}>v0.4.x の Basic Auth では User モデルはありません。表示は読み取り専用です。</div><div className="account-panel-actions"><button className="btn ghost" disabled>変更を保存 (Coming later)</button></div></Panel>:null}
      {tab==="セキュリティ"? <Panel className="account-panel"><div className="account-section-head"><ShieldCheck size={18}/><div><h3>セキュリティ</h3><p>管理画面へのアクセス保護。</p></div></div><div className="setting-row"><div><strong>SALESGATE_PASSWORD</strong><p>{envInfo.hasPassword? "設定済み — Basic認証が有効です":"未設定 — 認証なしで公開されています"}</p></div><Toggle checked={envInfo.hasPassword} onChange={()=>alert("環境変数 SALESGATE_PASSWORD で設定。Restart required")} label="パスワード認証"/></div><div className="setting-row"><div><strong>認証方式</strong><p>{envInfo.authType}</p></div><span style={{fontSize:10, color:"#7f90a7"}}>{envInfo.hasPassword? "Configured via environment":"Not configured"}</span></div><div className="security-box"><div><KeyRound size={17}/><span><strong>API / MCP Access Token</strong><small>Not available in current self-host auth (v0.4.x)</small></span></div><code>—</code><button className="icon-btn" disabled><Copy size={15}/></button></div><div className="modal-info" style={{margin:"0 14px 14px"}}>2FA / Token 再生成は今後のリリースで対応予定です。</div></Panel>:null}
      {tab==="セッション"? <Panel className="account-panel"><div className="account-section-head"><MonitorSmartphone size={18}/><div><h3>アクティブセッション</h3><p>SalesGateへログイン中のデバイス。</p></div></div><div className="empty-state" style={{minHeight:160,padding:20}}><strong>Session management is not available in v0.4.x</strong><span>現在のバージョンでは Basic Auth のため、複数デバイスのセッション管理は提供されていません。</span></div></Panel>:null}
    </div>
  </div>;
}
